# Build your Java project and run tests with Apache Maven

trigger:
- main

pool:
  vmImage: 'windows-2022'

steps:

# Maven Build
- task: Maven@4
  inputs:
    mavenPomFile: 'Javateam/pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'

# Copy JAR/WAR files to staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: 'Javateam/target'
    Contents: '*.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'